# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Portfolio
description: Portfolio of Utkarsh
baseurl: "/bay"
url: "https://eliottvincent.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: utkarshpsri@gmail.com
  
  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/Utkarsh_ps
      username: "@Utkarsh_ps"
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/utkarsh-ps/
    - type: github
      name: GitHub
      link: http://github.com/utkarsh231
    - type: rss
      name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
